runtime: python39  # or the version you are using
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
